# STORAGE INFO
STORAGE_PROVIDER: AWS
AWS_ACCESS_KEY_ID: AKIAJYBTFMGBKR2YOIDQ
AWS_SECRET_ACCESS_KEY: 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
S3_REGION: sa-east-1
S3_BUCKET: comtijolo

# INSTAGRAM INFO
INSTA_CLIENT_ID: 711328ea9f2445aaba774170195b0f0f
INSTA_CLIENT_SECRET: 5ac42197274547439ca7b8e09c10d1a2
INSTA_ACCESS_TOKEN: 687307262.711328e.daceb9a0e65642adae4eeeeeaa452660